### ISSUE TITLE
How can i get the parameter to modify the VINS configure file？

### ISSUE THREAD

**Issue by derekhe89** [slightech/MYNT-EYE-VINS-Sample#1]
First you should get the parameter of camera from the camera calibration file in SDK‘s setting folder, for example my camera calibration file is /mynteye-1.7-linux-x64-gcc5-opencv-3.2.0/settings/SN03861E120009070E.conf, use your camera parameter modefy the VINS configure.
Second you can get the parameter of camera and imu from imu instroduction in https://github.com/slightech/MYNT-EYE-SDK/blob/master/doc/mynteye-apidoc-1.7.pdf , and modify the VINS configure. If you want higher precision ， you should calibrate  it with kalibr.

**Comment by derekhe89** [comment]
First you should get the  parameter of camera from the camera calibration file in SDK‘s setting  folder,  for example my camera calibration file  is /mynteye-1.7-linux-x64-gcc5-opencv-3.2.0/settings/SN03861E120009070E.conf, use your camera parameter modefy the VINS configure.
Second you can get the parameter of camera and imu from imu instroduction in https://github.com/slightech/MYNT-EYE-SDK/blob/master/doc/mynteye-apidoc-1.7.pdf ,  and modify the VINS configure. If you want higher precision ， you should calibrate the it with  kalibr.

**Comment by tiralonghipol** [comment]
@derekhe89  It is written in the first page https://github.com/slightech/MYNT-EYE-VINS-Sample

you should have installed the SDK-2 package, then run
./samples/_output/bin/tutorials/get_img_params

you should get something like:

> ~/MYNT-EYE-SDK-2$ ./samples/_output/bin/tutorials/get_img_params
I0904 11:22:28.226672   955 utils.cc:26] Detecting MYNT EYE devices
I0904 11:22:28.498826   955 utils.cc:36] MYNT EYE devices:
I0904 11:22:28.498890   955 utils.cc:39]   index: 0, name: MYNT-EYE-S1000, sn: 4B4C212300090712
I0904 11:22:28.498909   955 utils.cc:47] Only one MYNT EYE device, select index: 0
I0904 11:22:28.524711   955 get_img_params.cc:25] Intrinsics left: {width: 752, height: 480, fx: 353.22566492145216444, fy: 353.75735542131320699, cx: 366.67073294703766351, cy: 231.36968104084658648, model: 0, coeffs: [-0.27325742409656251, 0.05734241315301845, -0.00073173963358416, -0.00032678641107056, 0.00000000000000000]}
I0904 11:22:28.524870   955 get_img_params.cc:26] Intrinsics right: {width: 752, height: 480, fx: 357.04379832336525169, fy: 357.48046276583062308, cx: 364.54397345244797179, cy: 226.98162088980953399, model: 0, coeffs: [-0.27670224321965647, 0.05681582139920396, 0.00045926505061012, -0.00037942448887334, 0.00000000000000000]}
I0904 11:22:28.524950   955 get_img_params.cc:28] Extrinsics right to left: {rotation: [0.99933163136069325, 0.00269644930337451, 0.03645572277612709, -0.00282028636428770, 0.99999042536033289, 0.00334591878024086, -0.03644635162535358, -0.00344649805090424, 0.99932966787961730], translation: [-119.76346766537703559, 0.66915465127051110, 3.82692076500526746]}
<
