### ISSUE TITLE
漂移

### ISSUE THREAD

**Issue by jixiedaima** [slightech/MYNT-EYE-VINS-Sample#2]
用小觅摄像头测试，漂移太厉害？

**Comment by YiChenCityU** [comment]
我也试了，静止漂移很厉害，是数据问题吧？

**Comment by jixiedaima** [comment]
摄像头没标定好，标定好感觉蛮困难的

**Comment by JHzss** [comment]
请问你们标定好了么，我的漂移也很严重，你们现在使用效果怎么样？

**Comment by sunzj** [comment]
放着不动就在不停的转圈。

**Comment by yangruixuan** [comment]
使用的时候注意几点，1、标定，可以参照相关说明进行，2、初始化的时候尽量找特征点丰富的环境，3、关闭IR，IR会对特征点提取有影响
